### PR TITLE
Conversion to JSON API

### PR DESCRIPTION
**Pull request by speedst3r**
Modified the methods to use the new JSON API from Advantage Air.

### CODE REVIEW

**Comment by smallsam** [comment]
@speedst3r thanks for this. Been out of action for a few months, starting to take a look at this now. Have you been using it much?

**Comment by speedst3r** [comment]
Not as yet, just testing from the command line. I haven't got around to having a go at creating a climate device so it integrates in HA as yet...

**Comment by smallsam** [comment]
No worries. Merging this as is for now. I've got most of a climate device together. Just need to merge in the latest home assistant release and test. I'll push that to my home-assistant fork when I've done some initial testing.

**Comment by speedst3r** [comment]
I'd be interested in that when you push it, no point duplicating work!

**Pull request merged**
